# Generated by Django 5.1.1 on 2024-09-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('tool_capacity', models.IntegerField()),
                ('tool_offset', models.FloatField()),
                ('feedrate', models.IntegerField()),
                ('tool_in_use', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_name', models.CharField(max_length=1)),
                ('max_acceleration', models.FloatField()),
                ('max_velocity', models.FloatField()),
                ('actual_position', models.FloatField()),
                ('target_position', models.FloatField()),
                ('distance_to_go', models.FloatField()),
                ('homed', models.BooleanField(default=False)),
                ('acceleration', models.FloatField()),
                ('velocity', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='machines.machine')),
            ],
        ),
    ]
